### Back Propogation using Pytorch

y = x^2

In [11]:
import torch

In [12]:
x = torch.tensor(4.0, requires_grad = True)

In [13]:
x

tensor(4., requires_grad=True)

In [14]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [15]:
### Back Propogation y = 2*x

y.backward() #Computes the gradient of current tensor wrt graph leaves.

In [16]:
print(x.grad)

tensor(8.)


In [18]:
lst = [[2.0,3.0,1.0], [4.,5.,3.],[7.,6.,4.]]
torch_input = torch.tensor(lst, requires_grad = True)

In [19]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [25]:
# y = x**3 + x**2
# After derivation, y = 3x**2 + 2x
y = torch_input**3 + torch_input**2

In [26]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [27]:
z = y.sum()

In [28]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [24]:
z.backward()

In [29]:
print(torch_input.grad)

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])


In [32]:
## How have we got these values?

In [30]:
3*2**2 + 2*2

16

In [31]:
3*3**2 + 2*3

33