## Pytorch

#### Tensor basics

A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [1]:
import torch

In [2]:
torch.__version__

'2.2.1+cu121'

In [3]:
import numpy as np

In [4]:
lst = [3,4,5,6]
arr = np.array(lst)

In [5]:
arr

array([3, 4, 5, 6])

In [6]:
arr.dtype

dtype('int32')

In [7]:
#Convert Numpy to pytorch tensors

In [9]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [10]:
#### Indexing similar to numpy
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [11]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [12]:
### Disadavantage of from_numpy. The array and tesors uses the same memory location

tensors[3] = 100

In [13]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [15]:
arr # numpy array is also changed as they share the same memory

array([  3,   4,   5, 100])

In [16]:
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [18]:
tensor_arr[3] = 120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120], dtype=torch.int32)
[  3   4   5 100]


In [21]:
## zeros and ones
torch.zeros(2,3, dtype = torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [22]:
torch.ones(2,3, dtype = torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [27]:
a = torch.tensor(np.arange(0,15).reshape(5,3))
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [33]:
a[0:2,0:2]

tensor([[0, 1],
        [3, 4]], dtype=torch.int32)

#### Arithemetic operations

In [35]:
a = torch.tensor([3,4,5], dtype = torch.float)
b = torch.tensor([4,5,6], dtype = torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [36]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [38]:
c = torch.zeros(3)
c

tensor([0., 0., 0.])

In [40]:
torch.add(a,b, out = c) # performing operation and storing in the some other variable
#shape of the output variable should be same

tensor([ 7.,  9., 11.])

In [41]:
c

tensor([ 7.,  9., 11.])

In [42]:
torch.add(a,b).sum()

tensor(27.)

#### Dot product and multi operations

In [43]:
x = torch.tensor([3,4,5], dtype = torch.float)
y = torch.tensor([4,5,6], dtype = torch.float)

In [45]:
x.mul(y) #simple multiplication

tensor([12., 20., 30.])

In [47]:
x.dot(y) #3*4 + 4*5 + 5*6

tensor(62.)

In [ ]:
#### Matrix multiplication

In [49]:
x = torch.tensor([[1,4,2], [1,5,5]], dtype = torch.float)
y = torch.tensor([[5,7], [8,6], [9,11]], dtype = torch.float)

In [50]:
torch.matmul(x,y) 

tensor([[55., 53.],
        [90., 92.]])

In [54]:
torch.mm(x,y) #similar to above matrix multiplication

tensor([[55., 53.],
        [90., 92.]])

In [53]:
x@y #similar to above matrix multiplication

tensor([[55., 53.],
        [90., 92.]])